bardsoftware/ace

lib/ace/editor.js, lib/ace/keyboard/textinput.js
=> Tell undo if it called via ctrl+z or manually

OWNERS
=> Added login to OWNERS

OWNERS
=> Added login into Owners

demo/summer-2016.html
=> Small refactoring

lib/ace/edit_session/bracket_match.js, lib/ace/editor.js, lib/ace/token_iterator.js
Now, i have problem with case that when bracket don't have a pair. In other cases, it works well.
=> Tkt 20 another version

lib/ace/edit_session/bracket_match.js, lib/ace/editor.js
=> Tkt 35. Add markers on brackets.

lib/ace/edit_session/bracket_match.js, lib/ace/editor.js
This marker may be appropriate? Or not?
@dbarashev
=> Add mismatch highlighting

lib/ace/ext/papeeria/katex-previewer.coffee, lib/ace/ext/papeeria/katex-previewer.js
@dbarashev KaTeX now seems to be loading on demand on first hotkey press. Please review.
=> Tkt 52 load KaTeX dynamically on first hotkey press

lib/ace/ext/papeeria/spellchecker.coffee, lib/ace/ext/papeeria/spellchecker.js
Added test json, rewrote check to search token in json instead of test it with regexp
=> Issue #54 Spellchecker frontend stuff

demo/summer-2016.html, lib/ace/ext/papeeria/papeeria_latex_highlight_rules.coffee, lib/ace/ext/papeeria/papeeria_latex_highlight_rules.js
=> Fixing plain text in equation context

lib/ace/ext/papeeria/latex_parsing_context_test.js, lib/ace/ext/papeeria/papeeria_latex_highlight_rules.coffee, lib/ace/ext/papeeria/papeeria_latex_highlight_rules.js
=> Fixed broken generic environment completions

lib/ace/ext/papeeria/katex-previewer.coffee, lib/ace/ext/papeeria/katex-previewer.js
@dbarashev I don't know if there is really anything to review here, but here's the fix.
=> Fixed `selectionHandler`

lib/ace/autocomplete/text_completer.js, lib/ace/ext/papeeria/tex_completer.coffee, lib/ace/ext/papeeria/tex_completer.js
- trigger tex completion only when prefix is \<any> or prefix length >= 3
- trigger basic text completion if prefix length >=3
- remove "local" from basic text completion
@khazhoyan @yanenkoa review?
re #98
=> Live autocompletion tweaks

lib/ace/ext/papeeria/tex_completer.coffee, lib/ace/ext/papeeria/tex_completer.js
=> Fixed issue #100

demo/summer-2016.html, lib/ace/ext/papeeria/spellchecker.coffee, lib/ace/ext/papeeria/spellchecker.js
split `updateSpellcheckingSession` into two methods
=> Changes in spellchecker interface

lib/ace/mode/latex_worker.js, lib/ace/mode/markdown.js, lib/ace/mode/markdown_worker.js, lib/ace/mode/papeeria_latex.js, lib/ace/mode/papeeria_worker.js, lib/ace/mode/text.js, lib/ace/mode/text_parser.js, lib/ace/mode/text_worker.js
=> Support spellchecking in markdown & text mode

lib/ace/ext/papeeria/spellchecker_popup.coffee, lib/ace/ext/papeeria/spellchecker_popup.js
=> Add callback to SpellcheckerPopup

lib/ace/ext/papeeria/spellchecker.coffee, lib/ace/ext/papeeria/spellchecker_test.js, lib/ace/mode/latex_parser.js, lib/ace/mode/latex_worker.js, lib/ace/mode/papeeria_worker.js, lib/ace/mode/text.js, lib/ace/mode/text_parser.js, lib/ace/mode/text_parser_test.js
re #115 
also made `LatexParser` extending `TextParser`
=> Tokenize using punctuation

lib/ace/ext/papeeria/spellchecker.coffee, lib/ace/ext/papeeria/spellchecker.js, lib/ace/ext/papeeria/spellchecker_popup.coffee, lib/ace/ext/papeeria/spellchecker_popup.js
changes needed by papeeria's PR
=> Remove the PopupActionManager abstraction

lib/ace/test/all.js
=> Run all tests from all.js

lib/ace/test/all.js
turns out my changes do nothing but run the tests in nested directories twice. My bad
=> Revert my genius PR

lib/ace/ext/papeeria/spellchecker.coffee, lib/ace/ext/papeeria/spellchecker.js, lib/ace/ext/papeeria/spellchecker_popup.coffee, lib/ace/ext/papeeria/spellchecker_popup.js
Made spellchecker_popup consistent with typo markers
and some changes required by the server side
=> Bugfix and changes for papeeria
